name: know_it
description: A healthy based game developed during the IFRAD Hackathon

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.1

  # state management
  flutter_riverpod: ^2.1.1

  # urls
  url_launcher: ^6.1.6

# fonts
  google_fonts: ^3.0.1

# navigation
  go_router: ^5.1.1

  # firebase

  # images
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2


  # extras
  flextras: ^0.0.2

  # animations
  animations: ^2.0.7

  # sharing
  share_plus: ^6.2.0 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
